### ISSUE TITLE
The ephemeral grader returns 502 when compilation fails

### ISSUE THREAD

**Issue by frcepeda** [omegaup/quark#4]
When making a request with an invalid `.idl` (e.g. with an illegal function name or a syntax error), the grader returns a 502 error from nginx instead of the error output from `libinteractive`.

Edit: Actually this happens with **any** compile error.

**Comment by lhchavez** [comment]
From the logs:

```
t=2018-06-02T16:19:19+0000 lvl=eror msg="Error creating input factory" err="\t\tRange(0, 500000) int K, int[K] type, long[K] index\n\n\t\t^\n``)'' expected but `Range' found (line 4:3)\n"
2018/06/02 16:19:19 http: panic serving 127.0.0.1:57140: runtime error: invalid memory address or nil pointer dereference
goroutine 3519103 [running]:
net/http.(*conn).serve.func1(0xc421e58320)
        /usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0xa8ba40, 0x10bf190)
        /usr/local/go/src/runtime/panic.go:502 +0x229
encoding/json.(*encodeState).marshal.func1(0xc420647810)
        /usr/local/go/src/encoding/json/encode.go:290 +0x13e
panic(0xa8ba40, 0x10bf190)
        /usr/local/go/src/runtime/panic.go:502 +0x229
math/big.(*Rat).Float64(0x0, 0x16, 0xa8dfe0)
        /usr/local/go/src/math/big/rat.go:281 +0x26
github.com/omegaup/quark/common.RationalToFloat(0x0, 0xb37548)
        /home/vagrant/quark/src/github.com/omegaup/quark/common/context.go:615 +0x2b
github.com/omegaup/quark/runner.(*RunResult).MarshalJSON(0xc421e08b00, 0xa8dfe0, 0xc421e08b00, 0x7f1f2ad2ef60, 0xc421e08b00, 0x52ce01)
        /home/vagrant/quark/src/github.com/omegaup/quark/runner/runner.go:171 +0x33
encoding/json.marshalerEncoder(0xc430d70840, 0xa8dfe0, 0xc421e08b00, 0x16, 0xc421e00100)
        /usr/local/go/src/encoding/json/encode.go:445 +0x9c
encoding/json.(*encodeState).reflectValue(0xc430d70840, 0xa8dfe0, 0xc421e08b00, 0x16, 0x100)
        /usr/local/go/src/encoding/json/encode.go:325 +0x82
encoding/json.(*encodeState).marshal(0xc430d70840, 0xa8dfe0, 0xc421e08b00, 0x100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:298 +0xa5
encoding/json.(*Encoder).Encode(0xc420647ae8, 0xa8dfe0, 0xc421e08b00, 0xb37548, 0xc)
        /usr/local/go/src/encoding/json/stream.go:200 +0x96
main.(*runHandler).addAndWaitForRun(0xc42014e250, 0xbf4500, 0xc4201340e0, 0xc422880800, 0xc4201aa580, 0xc420688390, 0xc420148a80, 0x0, 0x0)
        /home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-grader/ephemeral.go:94 +0x7cd
main.(*runHandler).ServeHTTP(0xc42014e250, 0xbf4500, 0xc4201340e0, 0xc422880800)
        /home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-grader/ephemeral.go:254 +0x663
net/http.(*ServeMux).ServeHTTP(0xc42024f860, 0xbf4500, 0xc4201340e0, 0xc422880800)
        /usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4202736c0, 0xbf4500, 0xc4201340e0, 0xc422880800)
        /usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc421e58320, 0xbf4c40, 0xc421e31b00)
        /usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x27b
```
